default_platform(:ios)

platform :ios do
  desc "TestFlight 배포"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "33KAKCQ9HT",
      issuer_id: "faa17191-6062-4977-ad9f-595259526ef5",
      key_filepath: "fastlane/AuthKey.p8",
    )

    increment_build_number(
      xcodeproj: "ios/LanguageDiary.xcodeproj"
    )

    build_app(
      workspace: "ios/languagediary.xcworkspace",
      scheme: "LanguageDiary",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "./build",
    )

    upload_to_testflight(api_key: api_key)
  end
end
