"""add_pronunciation_voice_id_to_user_profiles

Revision ID: 0acd4e4b496d
Revises: 0004
Create Date: 2026-02-26 23:29:41.757815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acd4e4b496d'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('pronunciation_voice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'voices', ['pronunciation_voice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'pronunciation_voice_id')
    # ### end Alembic commands ###
