"""add idx_diaries_deleted_at partial index

Revision ID: 143e44810bce
Revises: 001
Create Date: 2026-02-25 16:58:32.273798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143e44810bce'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_diaries_deleted_at', 'diaries', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_diaries_deleted_at', table_name='diaries', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
