"""add_fk_cefr_level_to_cefr_levels

Revision ID: 693f5c732f87
Revises: a86a70cb3ceb
Create Date: 2026-02-26 23:47:26.511139
"""
from typing import Sequence, Union

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '693f5c732f87'
down_revision: Union[str, None] = 'a86a70cb3ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
