"""add_origin_from_to_learning_cards

Revision ID: 6b5f59b248c1
Revises: b1c2d3e4f5a6
Create Date: 2026-03-02 21:03:32.345800
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5f59b248c1'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_cards', sa.Column('origin_from', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_cards', 'origin_from')
    # ### end Alembic commands ###
