"""add_cefr_levels_table

Revision ID: a86a70cb3ceb
Revises: 0acd4e4b496d
Create Date: 2026-02-26 23:47:19.388214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a86a70cb3ceb'
down_revision: Union[str, None] = '0acd4e4b496d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cefr_levels',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_foreign_key(None, 'user_language_levels', 'cefr_levels', ['cefr_level'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_language_levels', type_='foreignkey')
    op.drop_table('cefr_levels')
    # ### end Alembic commands ###
