"""add_word_scores_reference_text_to_pronunciation

Revision ID: ce3eddd056b2
Revises: ce917df0e540
Create Date: 2026-03-03 07:43:27.204153
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3eddd056b2'
down_revision: Union[str, None] = 'ce917df0e540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pronunciation_results', sa.Column('reference_text', sa.Text(), nullable=True))
    op.add_column('pronunciation_results', sa.Column('word_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pronunciation_results', 'word_scores')
    op.drop_column('pronunciation_results', 'reference_text')
    # ### end Alembic commands ###
