"""add example_audio_url to learning_cards

Revision ID: ce917df0e540
Revises: 441324b9e868
Create Date: 2026-03-02 23:12:51.940018
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce917df0e540'
down_revision: Union[str, None] = '441324b9e868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_cards', sa.Column('example_audio_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_cards', 'example_audio_url')
    # ### end Alembic commands ###
