"""add_title_to_diary

Revision ID: e581dc644ff3
Revises: 6b5f59b248c1
Create Date: 2026-03-02 21:13:47.979264
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e581dc644ff3'
down_revision: Union[str, None] = '6b5f59b248c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('title_original', sa.Text(), nullable=True))
    op.add_column('diaries', sa.Column('title_translated', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diaries', 'title_translated')
    op.drop_column('diaries', 'title_original')
    # ### end Alembic commands ###
